# Generated by Django 3.0.2 on 2020-01-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=60)),
                ('slug', models.CharField(max_length=60)),
                ('link', models.URLField()),
                ('content', models.TextField()),
                ('excerpt', models.TextField()),
            ],
        ),
    ]
